In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('customer_churn_data.xlsx')
data.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,No,Yes,23,Month-to-month,Bank transfer,49.85,1146.55,No
1,Female,0,Yes,No,43,Month-to-month,Mailed check,100.70,4330.10,Yes
2,Male,1,No,No,51,One year,Electronic check,97.33,4963.83,Yes
3,Male,1,No,No,72,Month-to-month,Credit card,101.38,7299.36,No
4,Male,1,No,No,25,Month-to-month,Electronic check,52.22,1305.50,Yes


In [4]:
data.columns  =['gender', 'seniorCitizen', 'partner', 'dependents', 'tenure',
       'contract', 'paymentMethod', 'monthlyCharges', 'totalCharges', 'churn']

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5880 entries, 0 to 5879
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gender          5880 non-null   object 
 1   seniorCitizen   5880 non-null   int64  
 2   partner         5880 non-null   object 
 3   dependents      5880 non-null   object 
 4   tenure          5880 non-null   int64  
 5   contract        5880 non-null   object 
 6   paymentMethod   5880 non-null   object 
 7   monthlyCharges  5880 non-null   float64
 8   totalCharges    5880 non-null   float64
 9   churn           5880 non-null   object 
dtypes: float64(2), int64(2), object(6)
memory usage: 459.5+ KB


In [6]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.gender.unique()

array(['Male', 'Female'], dtype=object)

In [8]:
data.seniorCitizen.unique()

array([0, 1])

In [9]:
data.partner.unique()

array(['No', 'Yes'], dtype=object)

In [10]:
data.dependents.unique()

array(['Yes', 'No'], dtype=object)

In [11]:
data.tenure.unique()

array([23, 43, 51, 72, 25, 35, 17, 18, 27, 15, 69, 42, 34, 48,  8, 10,  5,
       26, 62, 13,  9, 20, 57, 24, 33, 60, 64, 30, 14, 19, 71, 59, 67, 44,
       32, 11,  2, 68, 40, 46,  4, 38, 63, 29, 70, 52, 55, 66, 31, 61, 36,
       37, 47, 22, 39, 58,  7, 65,  6, 45,  1, 56, 21, 16, 49, 41,  3, 12,
       53, 28, 50, 54])

In [12]:
data.contract.unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [13]:
data.paymentMethod.unique()

array(['Bank transfer', 'Mailed check', 'Electronic check', 'Credit card'],
      dtype=object)

In [14]:
data.select_dtypes('O')

,gender,partner,dependents,contract,paymentMethod,churn
0,Male,No,Yes,Month-to-month,Bank transfer,No
1,Female,Yes,No,Month-to-month,Mailed check,Yes
2,Male,No,No,One year,Electronic check,Yes
3,Male,No,No,Month-to-month,Credit card,No
4,Male,No,No,Month-to-month,Electronic check,Yes
...,...,...,...,...,...,...
5875,Male,Yes,Yes,Month-to-month,Mailed check,No
5876,Male,No,No,One year,Mailed check,Yes
5877,Female,No,No,One year,Bank transfer,No
5878,Female,Yes,Yes,Month-to-month,Mailed check,No


In [15]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
encoded = ohe.fit_transform(data.select_dtypes('O').drop('churn',axis=1))

In [16]:
encoded_categories = pd.DataFrame(data = encoded.toarray(),columns=ohe.get_feature_names_out())

In [17]:
encoded_categories

,gender_Female,gender_Male,partner_No,partner_Yes,dependents_No,dependents_Yes,contract_Month-to-month,contract_One year,contract_Two year,paymentMethod_Bank transfer,paymentMethod_Credit card,paymentMethod_Electronic check,paymentMethod_Mailed check
0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
5876,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5877,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
5878,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0


In [18]:
numbered_data = data.select_dtypes('number')
numbered_data

,seniorCitizen,tenure,monthlyCharges,totalCharges
0,0,23,49.85,1146.55
1,0,43,100.70,4330.10
2,1,51,97.33,4963.83
3,1,72,101.38,7299.36
4,1,25,52.22,1305.50
...,...,...,...,...
5875,0,71,74.21,5268.91
5876,0,22,65.43,1439.46
5877,0,68,59.78,4065.04
5878,0,14,91.88,1286.32


In [19]:
df = pd.concat([numbered_data,encoded_categories],axis=1)

In [20]:
df = df.astype(float)

In [21]:
df

,seniorCitizen,tenure,monthlyCharges,totalCharges,gender_Female,gender_Male,partner_No,partner_Yes,dependents_No,dependents_Yes,contract_Month-to-month,contract_One year,contract_Two year,paymentMethod_Bank transfer,paymentMethod_Credit card,paymentMethod_Electronic check,paymentMethod_Mailed check
0,0.0,23.0,49.85,1146.55,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,43.0,100.70,4330.10,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,51.0,97.33,4963.83,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1.0,72.0,101.38,7299.36,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,25.0,52.22,1305.50,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5875,0.0,71.0,74.21,5268.91,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
5876,0.0,22.0,65.43,1439.46,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5877,0.0,68.0,59.78,4065.04,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
5878,0.0,14.0,91.88,1286.32,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0


In [22]:
X=df
y = data.churn.replace(['Yes', 'No'],[1,0])

C:\Users\hp\AppData\Local\Temp\ipykernel_9508\832918056.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = data.churn.replace(['Yes', 'No'],[1,0])


In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression
lr  = LogisticRegression()
lr.fit(X_train,y_train)

D:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [25]:
pred_y = lr.predict(X_train)

In [26]:
from sklearn.metrics import confusion_matrix, classification_report

In [27]:
confusion_matrix(y_train,pred_y)

array([[1555,  843],
       [1430,  876]])

In [31]:
y_train.value_counts()

churn
0    2398
1    2306
Name: count, dtype: int64

In [33]:
pred_y_test=lr.predict(X_test)

In [34]:
confusion_matrix(y_test,pred_y_test)

array([[361, 223],
       [391, 201]])

In [35]:
from sklearn.preprocessing import minmax_scale