In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeCV
from sklearn.metrics import r2_score

In [2]:
data = fetch_california_housing()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [5]:
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
X_train_scaled

array([[ 0.13350629,  0.50935748,  0.18106017, ..., -0.01082519,
        -0.80568191,  0.78093406],
       [-0.53221805, -0.67987313, -0.42262953, ..., -0.08931585,
        -1.33947268,  1.24526986],
       [ 0.1709897 , -0.36274497,  0.07312833, ..., -0.04480037,
        -0.49664515, -0.27755183],
       ...,
       [-0.49478713,  0.58863952, -0.59156984, ...,  0.01720102,
        -0.75885816,  0.60119118],
       [ 0.96717102, -1.07628333,  0.39014889, ...,  0.00482125,
         0.90338501, -1.18625198],
       [-0.68320166,  1.85715216, -0.82965604, ..., -0.0816717 ,
         0.99235014, -1.41592345]])

In [14]:
ridge_cv = RidgeCV(alphas=[0.01, 0.001,0.1, 1.0, 10.0], cv=5)
ridge_cv.fit(X_train_scaled, y_train)

RidgeCV(alphas=[0.01, 0.001, 0.1, 1.0, 10.0], cv=5)

In [21]:
ridge_cv.best_score_

np.float64(0.606586393145956)

In [11]:
from sklearn.linear_model import Ridge
ridge_model = Ridge(0.01)

In [17]:
ridge_model.fit(X_train_scaled,y_train)

Ridge(alpha=0.01)

In [18]:
ridge_model.score(X_train_scaled,y_train)

0.6093459727882049

In [ ]:
ridge_cv.

In [22]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train_scaled,y_train)

LinearRegression()

In [23]:
lr.score(X_train_scaled,y_train)

0.6093459727972159

In [58]:
df = pd.DataFrame({
    'City': ['New York', 'Paris', 'Tokyo', 'Paris'],
    'Rating': ['A', 'B', 'A', 'C']})

df


,City,Rating
0,New York,A
1,Paris,B
2,Tokyo,A
3,Paris,C


In [60]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# # 3. Configure the encoder to output a Pandas DataFrame directly
# encoder.set_output(transform="pandas")

# 4. Fit and transform the categorical columns
encoded_df = encoder.fit_transform(df[['City']])

print("One-Hot Encoded DataFrame:")

encoded_df

One-Hot Encoded DataFrame:


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [62]:
pd.get_dummies(df.City, dtype=int)

,New York,Paris,Tokyo
0,1,0,0
1,0,1,0
2,0,0,1
3,0,1,0


In [63]:
city = input("What is your city?")

What is your city? Paris


In [64]:
pd.get_dummies(city,dtype=int)

,Paris
0,1


In [67]:
encoder.transform([[city]])

C:\Users\Teacher\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1., 0.]])